sudo: required

language: c
env: OS=f25
services:
  - docker

cache:
  directories:
    - $HOME/MoxieLogic
  before_cache:
    - $HOME/MoxieLogic

before_install:
  - gem install package_cloud
  - find $HOME/MoxieLogic -type f

script:
  -

after_success:
  - find MoxieLogic -name \*rpm | xargs -n 1 package_cloud push MoxieLogic/moxiedev/fedora/25;

